$wallpaper = {{image}}
$background = rgb({{colors.surface.default.hex_stripped}})
$surface = rgba({{colors.surface_container.default.hex_stripped}}f2)
$accent = rgba({{colors.tertiary.default.hex_stripped}}f2)
$text = rgba({{colors.on_surface.default.hex_stripped}}f2)
$text2 = rgba({{colors.secondary_fixed.default.hex_stripped}}f2)
