# HyDE lock layout: https://github.com/HyDE-Project/HyDE (hyprlock/HyDE.conf)
source = ~/.config/hypr/colors-hyprlock.conf

$font = JetBrainsMono Nerd Font

general {
  hide_cursor = true
}

background {
  path = $wallpaper
  color = $background
  blur_passes = 2
}

# time
label {
  text = $TIME
  color = $text
  font_size = 90
  font_family = $font
  position = -30, 0
  halign = right
  valign = top
}

# date
label {
  text = cmd[update:43200000] date +"%A, %d %B %Y"
  color = $text2
  font_size = 25
  font_family = $font
  position = -30, -150
  halign = right
  valign = top
}

# greeting
label {
  text = cmd[update:60000] echo "Good $(date +%H | awk '{if ($1 < 12) print "Morning"; else if ($1 < 18) print "Afternoon"; else print "Evening"}'), $USER"
  color = $text
  font_size = 20
  font_family = $font Bold
  position = 0, -16%
  halign = center
  valign = center
}

input-field {
  size = 200, 50
  outline_thickness = 3
  dots_size = 0.33
  dots_spacing = 0.15
  dots_center = true
  outer_color = $accent
  inner_color = $surface
  font_color = $text
  fade_on_empty = true
  fade_timeout = 1000
  placeholder_text = <i>Input Password...</i>
  rounding = -1
  check_color = $accent
  fail_color = rgba(FF0000FF)
  fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
  swap_font_color = true
  position = 0, 4.5%
  halign = center
  valign = bottom
}

# now playing
label {
  text = cmd[update:1000] playerctl metadata --format '{{title}}  {{artist}}' 2>/dev/null
  color = $text2
  font_size = 15
  font_family = $font
  position = 0, 0
  halign = center
  valign = bottom
}

# keyboard layout
label {
  text = $LAYOUT
  color = $accent
  font_size = 20
  font_family = $font
  position = -2%, 1%
  halign = right
  valign = bottom
}
